#!/bin/sh
API_NAME=rlwm-api

if [ -f ./.env ]; then . ./.env ; fi
export DB_DATABASE=$DB_DATABASE
export DB_USER=$DB_USER
export DB_PASSWORD=$DB_PASSWORD
export DB_PORT=$DB_PORT
export DB_HOST=$DB_HOST
export PORT=$PORT

if [ "$1" = "api-dev" ]; then cd api; node dev-watch.js ; EXITCODE=$? ; cd .. ; exit $EXITCODE ; fi
if [ "$1" = "api-build" ]; then cd api; yarn build ; EXITCODE=$? ; cd .. ; exit $EXITCODE ; fi

echo "Command not found"
