import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthenticationProvider from '@/utils/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'RocketLab Next Template',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthenticationProvider>{children} </AuthenticationProvider>
      </body>
    </html>
  )
}
